export const states = [
  { value: '',   name: 'All', population: 0 },
  { value: 'AL', name: 'Alabama', population: 95 },
  { value: 'AK', name: 'Alaska', population: 1 },
  { value: 'AZ', name: 'Arizona', population: 60 },
  { value: 'AR', name: 'Arkansas', population: 57 },
  { value: 'CA', name: 'California', population: 251 },
  { value: 'CO', name: 'Colorado', population: 52 },
  { value: 'CT', name: 'Connecticut', population: 741 },
  { value: "DC", name: "Washington DC", population: 11011 },
  { value: 'DE', name: 'Delaware', population: 485 },
  { value: 'FL', name: 'Florida', population: 378 },
  { value: 'GA', name: 'Georgia', population: 177 },
  { value: 'HI', name: 'Hawaii', population: 222 },
  { value: 'ID', name: 'Idaho', population: 20 },
  { value: 'IL', name: 'Illinois', population: 231 },
  { value: 'IN', name: 'Indiana', population: 184 },
  { value: 'IA', name: 'Iowa', population: 55 },
  { value: 'KS', name: 'Kansas', population: 36 },
  { value: 'KY', name: 'Kentucky', population: 112 },
  { value: 'LS', name: 'Louisiana', population: 108 },
  { value: 'ME', name: 'Maine', population: 43 },
  { value: 'MD', name: 'Maryland', population: 618 },
  { value: 'MA', name: 'Massachusetts', population: 871 },
  { value: 'MI', name: 'Michigan', population: 175 },
  { value: 'MN', name: 'Minnesota', population: 68 },
  { value: 'MS', name: 'Mississippi', population: 63 },
  { value: 'MO', name: 'Missouri', population: 88 },
  { value: 'MT', name: 'Montana', population: 7 },
  { value: 'NE', name: 'Nebraska', population: 24 },
  { value: 'NV', name: 'Nevada', population: 26 },
  { value: 'NH', name: 'New Hampshire', population: 148 },
  { value: 'NJ', name: 'New Jersey', population: 1218 },
  { value: 'NM', name: 'New Mexico', population: 17 },
  { value: 'NY', name: 'New York', population: 420 },
  { value: 'NC', name: 'North Carolina', population: 206 },
  { value: 'ND', name: 'North Dakota', population: 10 },
  { value: 'OH', name: 'Ohio', population: 284 },
  { value: 'OK', name: 'Oklahoma', population: 57 },
  { value: 'OR', name: 'Oregon', population: 41 },
  { value: 'PA', name: 'Pennsylvania', population: 286 },
  { value: 'RI', name: 'Rhode Island', population: 1021 },
  { value: 'SC', name: 'South Carolina', population: 162 },
  { value: 'SD', name: 'South Dakota', population: 11 },
  { value: 'TN', name: 'Tennessee', population: 160 },
  { value: 'TX', name: 'Texas', population: 105 },
  { value: 'UT', name: 'Utah', population: 36 },
  { value: 'VT', name: 'Vermont', population: 67 },
  { value: 'VA', name: 'Virginia', population: 212 },
  { value: 'WA', name: 'Washington', population: 107 },
  { value: 'WV', name: 'West Virginia', population: 76 },
  { value: 'WI', name: 'Wisconsin', population: 106 },
  { value: 'WY', name: 'Wyoming', population: 6 }
];